name: Build and Deploy Microservices

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy-movie-management:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build MovieManagement with Maven
        working-directory: MovieManagement  # Replace with the actual directory path
        run: mvn package --file pom.xml

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v2
        with:
          name: movie-management-jar
          path: '${{ github.workspace }}/MovieManagement/target/*.jar'

      - name: Deploy MovieManagement to Azure Web App
        id: deploy-movie-management-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'MovieBookingApplicationBackend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_944CDBC77FE14E8E82DC9DE160D563CD }}
          package: Movie-Management/target/*.jar


    
      # Similar steps as above for Eureka microservice
